### ISSUE TITLE
Having error in running 4th cell

### ISSUE THREAD

**Issue by approjecthub** [llSourcell/Sentiment_Analysis#11]
I am pasting the error message below:

---------------------------------------------------------------------------
TweepError                                Traceback (most recent call last)
<ipython-input-30-c2189589fb5b> in <module>()
      4 api = tweepy.API(auth)
      5 
----> 6 tweets = api.search('Artificial Intelligence', count=200)
      7 
      8 

/usr/local/lib/python3.6/dist-packages/tweepy/binder.py in _call(*args, **kwargs)
    248             return method
    249         else:
--> 250             return method.execute()
    251 
    252     # Set pagination mode

/usr/local/lib/python3.6/dist-packages/tweepy/binder.py in execute(self)
    232                     raise RateLimitError(error_msg, resp)
    233                 else:
--> 234                     raise TweepError(error_msg, resp, api_code=api_error_code)
    235 
    236             # Parse the response payload

TweepError: [{'code': 215, 'message': 'Bad Authentication data.'}]

**Comment by cvaldez83** [comment]
I didn't get this error, however, have you tried logging into your twitter developer account and regenerating your app's 'Consumer API keys' as well as 'Access token & access token secret'?  That's all I can think of since I see you have a 'RateLimitError' in your output.

**Comment by approjecthub** [comment]
No, I haven't done that. I think that was the problem behind this error.
Thanks for this info.
