### ISSUE TITLE
Update the source code containing nltk.download('lexicon') 

### ISSUE THREAD

**Issue by AbhisekGanguly** [llSourcell/Sentiment_Analysis#6]
hey Siraj!!!
your code containing **nltk.download('lexicon')** is not working anymore.
you should update it with **nlkt.download('vader-lexicon')**

`import nlkt
nltk.download('vader-lexicon')`

cheers!!!

Love from India,
Abhisek Ganguly

**Comment by ayushs136** [comment]
Yeah, you are right!

**Comment by bsirmacek** [comment]
nltk.download('vader_lexicon') works
